baseURL = "https://www.amybell.info/"
title = "Amy Bell"
languageCode = "en"
enableInlineShortcodes = true
theme = "soho"

summarylength = 10
enableEmoji = true

[params]
author = "Amy Bell"
description = "Data Scientist"
homepage = "homepage/home.md"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/AmyBanff.jpg"

copyright = "Amy Bell"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
themeColor = "#2f523e"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/syntax.css", "css/custom.css"]
customJs = ["js/blog.js"]

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/amy-bell-/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/amygbe"

  #[[params.socialIcons]]
  #icon = "fa-twitter"
  #title = "Twitter"
  #url = "#"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

  [[menu.main]]
  name = "Contact Me"
  identifier = "contact"
  weight = 300
  url = "/contact/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]


 [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = false # true if you want to use monokai styling
  #style = "monokai"
  tabWidth = 4
